### PR TITLE
Fix @storybook/addons does not exist anymore

### PR DESCRIPTION
**Pull request by Kwintijn**

### CODE REVIEW

**Comment by bitttttten** [comment]
thanks for the patch! in which version did this change? as we'd also need to update the docs and also the peer dependencies so people know which version to install

**Comment by Kwintijn** [comment]
According to the NPM registry it's discontinued as of Storybook v8.0

**Comment by Adrii77** [comment]
Upgrading to storybook@8.2.0 caused an error about storybook/addons.

Capture d’écran 2024-07-10 à 10 51 42

**Comment by Adrii77** [comment]
up ? 👼🏻

**Comment by bitttttten** [comment]
thanks @Kwintijn , i will need to add either peerDependencies or a note in the docs. when i'm back to my laptop i can do this, otherwise feel free to upgrade this PR to include either of these and then it'll be ready to merge. thanks ❤️

**Pull request merged**
